# https://github.com/bbatsov/ruby-style-guide

AllCops:
  Exclude:
    - 'log/**/*'
    - 'bin/**/*'
    - 'build/**/*'
    - 'data/**/*'
    - 'node_modules/**/*'

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - 'source/feed.xml.builder'
    - 'spec/**/*'

Style/MixinUsage:
  Exclude:
    - 'spec/helpers/custom_helpers_spec.rb'

Style/DoubleNegation:
  Enabled: false

# Metrics/AbcSize:
#   Max: 30
#   Exclude:
#   - 'db/**/*'

# Metrics/MethodLength:
#   Max: 20
#   Exclude:
#     - 'db/**/*'
#
# Metrics/ClassLength:
#   Max: 150
# #   Exclude:
# #     - ''
#
# Metrics/ParameterLists:
#   Exclude:

Style/StringLiterals:
  EnforcedStyle: double_quotes
  Enabled: true

# Style/PredicateName:
#   Enabled: false
#
# Style/AccessorMethodName:
#   Enabled: false
#
# Style/DoubleNegation:
#   Enabled: false
#
# Style/ClassAndModuleChildren:
#   Enabled: false
